name: Compile LaTeX to PDF and Deploy to GitHub Pages

on:
  push:
    paths:
      - '**/*.tex'  # Triggers when any .tex file is updated
  workflow_dispatch:  # Optional, allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile LaTeX to PDF
        run: pdflatex -interaction=nonstopmode -output-directory=. cv.tex

      - name: Move PDF to GitHub Pages Directory
        run: mv cv.pdf ./docs/cv.pdf  # Adjust path if needed based on your GitHub Pages config

      - name: Commit and push generated PDF
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/cv.pdf  # Adjust path if needed
          git commit -m 'Update CV PDF for GitHub Pages'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
