name: Compile LaTeX to PDF

on:
  push:
    paths:
      - '**/*.tex'  # Triggers when any .tex file is updated
  workflow_dispatch:  # Optional, allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile LaTeX to PDF
        run: pdflatex -interaction=nonstopmode -output-directory=. cv.tex

      - name: Commit and push generated PDF
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add cv.pdf
          git commit -m 'Automated PDF generation from LaTeX'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
